# Generated by Django 3.2.6 on 2021-11-20 11:52

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'payhere_user',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PayHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('memo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pay_history',
                'managed': False,
            },
        ),
    ]
